/**
* Generated by PluginGenerator from webgme on Wed Aug 19 2015 15:04:06 GMT-0500 (Central Daylight Time).
*/

define([], function () {
    'use strict';
    return {
        'FCO': '/1',
    };
});